// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_fq83uuzxlD-b2ssKyKAGUufQf34e0QM',
    appId: '1:417057707230:web:4bfe314b9b9968be98de4f',
    messagingSenderId: '417057707230',
    projectId: 'track-hostel',
    authDomain: 'track-hostel.firebaseapp.com',
    storageBucket: 'track-hostel.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcAkxiYqKOFgWN-kjEbsy99Z2ek1DG3jk',
    appId: '1:417057707230:android:d34245c80a71a27f98de4f',
    messagingSenderId: '417057707230',
    projectId: 'track-hostel',
    storageBucket: 'track-hostel.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8zCyQcOPFeFPiymziGb-QB-CQo8XTBtw',
    appId: '1:417057707230:ios:0ea233e9407daf8998de4f',
    messagingSenderId: '417057707230',
    projectId: 'track-hostel',
    storageBucket: 'track-hostel.appspot.com',
    iosBundleId: 'com.s4k1l.trackhostel',
  );
}
